### PR TITLE
Update CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by Genius398**

### CODE REVIEW

**Comment by Genius398** [comment]
@somePythonProgrammer can you merge this

**Comment by somePythonProgrammer** [comment]
Yes

**Comment by somePythonProgrammer** [comment]
I need write access for that.

**Comment by somePythonProgrammer** [comment]
Please make me a maintainer so that I can merge it.

**Comment by Genius398** [comment]
> Please make me a maintainer so that I can merge it.

now?

**Comment by somePythonProgrammer** [comment]
yes. I am merging...

**Comment by somePythonProgrammer** [comment]
done!

**Comment by Genius398** [comment]
>

> done!

 Amazing! So, now you can merge pull requests. So, if needed, I will ping to merge. Or if it says that all checks are completed, you can merge it. If anything goes wrong, I will fix it. 


Thanks!

**Comment by Genius398** [comment]
@somePythonProgrammer lol

**Comment by somePythonProgrammer** [comment]
image

What are you doing?

**Comment by Genius398** [comment]
> 
> image
> 
> What are you doing?

Yes. The something for a lol

**Pull request merged**
